// MbtilesProvider integration test against the synthetic world.mbtiles
// (tests/data/map/, generated by make_test_mbtiles.py). Verifies: metadata
// read, a known-good tile round-trips as a real image, malformed and
// out-of-range tile ids degrade to a placeholder rather than crashing or
// returning null.
// GCS is DAL D-equivalent (COMPLIANCE.md §A.2); no RTM/@req trace obligation applies here.

#ifndef UAOP_MBTILES_PATH
#define UAOP_MBTILES_PATH ""
#endif

#include <cassert>
#include <cstdlib>
#include <iostream>

#include <QGuiApplication>
#include <QSize>

#include "map/MbtilesProvider.h"

int main(int argc, char* argv[]) {
    // QGuiApplication, not QCoreApplication: the placeholder-tile path paints
    // text (QPainter::drawText), which needs a font/platform backend — a
    // bare QCoreApplication crashes there with no diagnostic. offscreen keeps
    // this headless, matching the gcs.selfcheck pattern in main.cpp.
    if (!qEnvironmentVariableIsSet("QT_QPA_PLATFORM")) {
        qputenv("QT_QPA_PLATFORM", "offscreen");
    }
    QGuiApplication app(argc, argv);

    uaop::gcs::map::MbtilesProvider provider(QStringLiteral(UAOP_MBTILES_PATH));
    assert(provider.isOpen());
    assert(provider.minZoom() == 0);
    assert(provider.maxZoom() == 3);

    QSize size;
    const QImage tile = provider.requestImage("0/0/0", &size, QSize());
    assert(!tile.isNull());
    assert(tile.width() == 256 && tile.height() == 256);
    assert(size == QSize(256, 256));

    // Malformed id must not crash and must not return a null image.
    const QImage bad = provider.requestImage("not-a-tile", &size, QSize());
    assert(!bad.isNull());

    // In-range-format but nonexistent tile (z beyond maxZoom) degrades gracefully.
    const QImage missing = provider.requestImage("9/1/1", &size, QSize());
    assert(!missing.isNull());

    std::cout << "mbtiles_provider_test: all assertions passed\n";
    return EXIT_SUCCESS;
}
