#!/usr/bin/env python3
"""RTM generator + annotation lint (COMPLIANCE.md section A.3, UAOP-NFR-009, R3/F20).

Scans source for traceability annotations:
    // @req: UAOP-HLR-001  <text>        (also UAOP-LLR-*, UAOP-NFR-*)
    // @test: UAOP-TC-001-A  <text>

Modes:
    --check     lint mode for CI: annotations must reference requirement IDs that
                exist in PRODUCT_REQUIREMENTS.md; placeholder IDs (UAOP-TPL-*) are
                allowed only inside tools/service-template/.
    (default)   generate docs/compliance/DO-178C/RTM.md from the scan.

DO-330 posture: deterministic, versioned, self-checking output — this tool is a
qualification candidate the moment its output enters certification data.
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SCAN_DIRS = ["api", "backend", "middleware", "frontend", "tools", "plugins", "integrations"]
CODE_EXT = {".c", ".cc", ".cpp", ".h", ".hpp", ".py", ".qml", ".proto"}
TEMPLATE_DIR = REPO / "tools" / "service-template"
ANN_RE = re.compile(r"@(req|test):\s*(UAOP-[A-Z]+-[\w-]+)\s*(.*)")
REQ_DOC = REPO / "docs" / "00_Project_Foundation" / "PRODUCT_REQUIREMENTS.md"
REQ_ID_RE = re.compile(r"\bUAOP-(?:HLR|NFR)-\d+\b")


def scan() -> list[dict]:
    found = []
    for d in SCAN_DIRS:
        base = REPO / d
        if not base.is_dir():
            continue
        for p in base.rglob("*"):
            if not p.is_file() or p.suffix.lower() not in CODE_EXT:
                continue
            if "build" in p.parts or "__pycache__" in p.parts:
                continue
            for lineno, line in enumerate(
                    p.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                m = ANN_RE.search(line)
                if m:
                    found.append({
                        "kind": m.group(1),
                        "id": m.group(2),
                        "text": m.group(3).strip(),
                        "file": p.relative_to(REPO).as_posix(),
                        "line": lineno,
                        "in_template": TEMPLATE_DIR in p.parents,
                    })
    return found


def known_requirement_ids() -> set[str]:
    return set(REQ_ID_RE.findall(REQ_DOC.read_text(encoding="utf-8")))


def check(annotations: list[dict]) -> int:
    known = known_requirement_ids()
    errors = []
    for a in annotations:
        if a["id"].startswith("UAOP-TPL-"):
            if not a["in_template"]:
                errors.append(f"{a['file']}:{a['line']}: placeholder ID {a['id']} "
                              f"outside tools/service-template/")
            continue
        if a["in_template"]:
            errors.append(f"{a['file']}:{a['line']}: real requirement ID {a['id']} inside the "
                          f"template — template code must never satisfy a real trace")
            continue
        if a["kind"] == "req" and a["id"] not in known:
            errors.append(f"{a['file']}:{a['line']}: @req references {a['id']} which is not "
                          f"defined in PRODUCT_REQUIREMENTS.md")
    if errors:
        print("ANNOTATION LINT FAILED (UAOP-NFR-009):")
        for e in errors:
            print(f"  {e}")
        return 1
    real = [a for a in annotations if not a["id"].startswith("UAOP-TPL-")]
    print(f"annotation lint: OK ({len(real)} traced annotations, "
          f"{len(annotations) - len(real)} template placeholders, {len(known)} known requirement IDs)")
    return 0


def generate(annotations: list[dict]) -> int:
    out = REPO / "docs" / "compliance" / "DO-178C" / "RTM.md"
    real = [a for a in annotations if not a["id"].startswith("UAOP-TPL-")]
    by_id: dict[str, list[dict]] = {}
    for a in real:
        by_id.setdefault(a["id"], []).append(a)

    lines = [
        "# Requirements Traceability Matrix (generated — do not edit)",
        "",
        f"Generated by `compliance/tools/rtm-generator/rtm_gen.py` on {date.today().isoformat()}. "
        f"Source of requirement IDs: PRODUCT_REQUIREMENTS.md. Regenerate; never hand-edit.",
        "",
        "| Requirement / Test ID | Kind | Location | Annotation text |",
        "|---|---|---|---|",
    ]
    for rid in sorted(by_id):
        for a in by_id[rid]:
            lines.append(f"| {rid} | @{a['kind']} | `{a['file']}:{a['line']}` | {a['text']} |")
    if not real:
        lines.append("| _none yet_ | — | — | first annotations land with milestone M2 |")

    covered = {a["id"] for a in real if a["kind"] == "req"}
    lines += ["", f"**Coverage:** {len(covered)} requirement IDs carry code annotations "
                  f"(Phase 1 gate target: ≥ 20 HLRs — ROADMAP.md)."]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"RTM written: {out.relative_to(REPO)} ({len(real)} annotations, {len(covered)} IDs)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="lint only (CI mode)")
    args = parser.parse_args()
    annotations = scan()
    rc = check(annotations)
    if args.check or rc != 0:
        return rc
    return generate(annotations)


if __name__ == "__main__":
    sys.exit(main())
